spring:
    application:
        name: restaurant-service

server:
  port: 8082

eureka:
 client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
 instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}