server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
     preferIpAddress: true
     instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
